import type { ExchangeFeature, ExchangeCategory } from './exchange-types';

export const EXCHANGE_CATEGORIES: ExchangeCategory[] = [
  {
    id: 'markets',
    titleEn: 'Markets',
    titleRu: 'Рынки и торговля',
    features: [
      { slug: 'spot-markets', titleEn: 'Spot Markets', titleRu: 'Спотовые рынки', kind: 'table' },
      { slug: 'spot-trade', titleEn: 'Spot Trade', titleRu: 'Спотовая торговля', kind: 'trade' },
      { slug: 'futures-usd', titleEn: 'USD-M Futures', titleRu: 'Фьючерсы USDT', kind: 'trade' },
      { slug: 'futures-coin', titleEn: 'Coin-M Futures', titleRu: 'Фьючерсы Coin-M', kind: 'trade' },
      { slug: 'perpetual', titleEn: 'Perpetual Swaps', titleRu: 'Бессрочные контракты', kind: 'trade' },
      { slug: 'options', titleEn: 'Options', titleRu: 'Опционы', kind: 'trade' },
      { slug: 'options-chain', titleEn: 'Options Chain', titleRu: 'Цепочка опционов', kind: 'table' },
      { slug: 'margin-cross', titleEn: 'Cross Margin', titleRu: 'Кросс-маржа', kind: 'trade' },
      { slug: 'margin-isolated', titleEn: 'Isolated Margin', titleRu: 'Изолированная маржа', kind: 'trade' },
      { slug: 'convert', titleEn: 'Convert', titleRu: 'Конвертация', kind: 'form' },
      { slug: 'block-trade', titleEn: 'Block Trade', titleRu: 'Блок-сделки', kind: 'form' },
      { slug: 'otc-desk', titleEn: 'OTC Desk', titleRu: 'OTC-деск', kind: 'form' },
      { slug: 'p2p-market', titleEn: 'P2P Market', titleRu: 'P2P маркет', kind: 'link', href: '/market' },
      { slug: 'p2p-express', titleEn: 'P2P Express', titleRu: 'P2P экспресс', kind: 'form' },
      { slug: 'grid-spot', titleEn: 'Spot Grid', titleRu: 'Спотовый грид', kind: 'bot' },
      { slug: 'grid-futures', titleEn: 'Futures Grid', titleRu: 'Фьючерсный грид', kind: 'bot' },
      { slug: 'dca-bot', titleEn: 'DCA Bot', titleRu: 'DCA-бот', kind: 'bot' },
      { slug: 'twap', titleEn: 'TWAP Orders', titleRu: 'TWAP-ордера', kind: 'form' },
      { slug: 'vwap', titleEn: 'VWAP Orders', titleRu: 'VWAP-ордера', kind: 'form' },
      { slug: 'iceberg', titleEn: 'Iceberg Orders', titleRu: 'Айсберг-ордера', kind: 'form' },
      { slug: 'trailing-stop', titleEn: 'Trailing Stop', titleRu: 'Трейлинг-стоп', kind: 'form' },
      { slug: 'oco', titleEn: 'OCO Orders', titleRu: 'OCO-ордера', kind: 'form' },
      { slug: 'scaled-orders', titleEn: 'Scaled Orders', titleRu: 'Лесенка ордеров', kind: 'form' },
      { slug: 'copy-trading', titleEn: 'Copy Trading', titleRu: 'Копитрейдинг', kind: 'table' },
      { slug: 'signal-trading', titleEn: 'Signal Trading', titleRu: 'Сигнальная торговля', kind: 'table' },
      { slug: 'strategy-marketplace', titleEn: 'Strategy Marketplace', titleRu: 'Маркетплейс стратегий', kind: 'table' },
      { slug: 'leaderboard', titleEn: 'Trader Leaderboard', titleRu: 'Рейтинг трейдеров', kind: 'table' },
      { slug: 'heatmaps', titleEn: 'Market Heatmap', titleRu: 'Тепловая карта', kind: 'dashboard' },
      { slug: 'screener', titleEn: 'Market Screener', titleRu: 'Скринер рынков', kind: 'table' },
      { slug: 'new-listings', titleEn: 'New Listings', titleRu: 'Новые листинги', kind: 'table' },
      { slug: 'delistings', titleEn: 'Delistings', titleRu: 'Делистинги', kind: 'table' },
      { slug: 'pair-info', titleEn: 'Pair Info', titleRu: 'Информация о паре', kind: 'dashboard' },
      { slug: 'orderbook-depth', titleEn: 'Order Book Depth', titleRu: 'Глубина стакана', kind: 'dashboard' },
      { slug: 'recent-trades', titleEn: 'Recent Trades', titleRu: 'Лента сделок', kind: 'table' },
      { slug: 'funding-rates', titleEn: 'Funding Rates', titleRu: 'Ставки фандинга', kind: 'table' },
      { slug: 'open-interest', titleEn: 'Open Interest', titleRu: 'Открытый интерес', kind: 'dashboard' },
      { slug: 'liquidations', titleEn: 'Liquidations', titleRu: 'Ликвидации', kind: 'table' },
      { slug: 'basis', titleEn: 'Basis Monitor', titleRu: 'Монитор базиса', kind: 'dashboard' },
    ],
  },
  {
    id: 'orders',
    titleEn: 'Orders',
    titleRu: 'Ордера и история',
    features: [
      { slug: 'open-orders', titleEn: 'Open Orders', titleRu: 'Открытые ордера', kind: 'table' },
      { slug: 'order-history', titleEn: 'Order History', titleRu: 'История ордеров', kind: 'table' },
      { slug: 'trade-history', titleEn: 'Trade History', titleRu: 'История сделок', kind: 'table' },
      { slug: 'position-history', titleEn: 'Position History', titleRu: 'История позиций', kind: 'table' },
      { slug: 'funding-history', titleEn: 'Funding History', titleRu: 'История фандинга', kind: 'table' },
      { slug: 'liquidation-history', titleEn: 'Liquidation History', titleRu: 'История ликвидаций', kind: 'table' },
      { slug: 'transaction-history', titleEn: 'Transaction History', titleRu: 'История транзакций', kind: 'table' },
      { slug: 'deposit-history', titleEn: 'Deposit History', titleRu: 'История депозитов', kind: 'table' },
      { slug: 'withdraw-history', titleEn: 'Withdraw History', titleRu: 'История выводов', kind: 'table' },
      { slug: 'transfer-history', titleEn: 'Transfer History', titleRu: 'История переводов', kind: 'table' },
      { slug: 'p2p-orders', titleEn: 'P2P Orders', titleRu: 'P2P ордера', kind: 'link', href: '/deals' },
      { slug: 'p2p-ads', titleEn: 'My Ads', titleRu: 'Мои объявления', kind: 'link', href: '/ads' },
      { slug: 'conditional-orders', titleEn: 'Conditional Orders', titleRu: 'Условные ордера', kind: 'table' },
      { slug: 'algo-orders', titleEn: 'Algo Orders', titleRu: 'Алго-ордера', kind: 'table' },
      { slug: 'bot-orders', titleEn: 'Bot Orders', titleRu: 'Ордера ботов', kind: 'table' },
      { slug: 'fill-reports', titleEn: 'Fill Reports', titleRu: 'Отчёты исполнений', kind: 'table' },
      { slug: 'export-csv', titleEn: 'Export CSV', titleRu: 'Экспорт CSV', kind: 'form' },
      { slug: 'tax-lots', titleEn: 'Tax Lots', titleRu: 'Налоговые лоты', kind: 'table' },
    ],
  },
  {
    id: 'wallet',
    titleEn: 'Wallet',
    titleRu: 'Кошелёк и финансы',
    features: [
      { slug: 'overview', titleEn: 'Asset Overview', titleRu: 'Обзор активов', kind: 'link', href: '/wallet' },
      { slug: 'spot-wallet', titleEn: 'Spot Wallet', titleRu: 'Спотовый кошелёк', kind: 'dashboard' },
      { slug: 'futures-wallet', titleEn: 'Futures Wallet', titleRu: 'Фьючерсный кошелёк', kind: 'dashboard' },
      { slug: 'funding-wallet', titleEn: 'Funding Wallet', titleRu: 'Фандинг-кошелёк', kind: 'dashboard' },
      { slug: 'earn-wallet', titleEn: 'Earn Wallet', titleRu: 'Earn-кошелёк', kind: 'dashboard' },
      { slug: 'deposit', titleEn: 'Deposit', titleRu: 'Депозит', kind: 'form' },
      { slug: 'withdraw', titleEn: 'Withdraw', titleRu: 'Вывод', kind: 'form' },
      { slug: 'internal-transfer', titleEn: 'Internal Transfer', titleRu: 'Внутренний перевод', kind: 'form' },
      { slug: 'payment-methods', titleEn: 'Payment Methods', titleRu: 'Способы оплаты', kind: 'link', href: '/payment-methods' },
      { slug: 'fiat-gateway', titleEn: 'Fiat Gateway', titleRu: 'Фиатный шлюз', kind: 'form' },
      { slug: 'crypto-address-book', titleEn: 'Address Book', titleRu: 'Адресная книга', kind: 'table' },
      { slug: 'whitelist', titleEn: 'Withdraw Whitelist', titleRu: 'Белый список выводов', kind: 'table' },
      { slug: 'travel-rule', titleEn: 'Travel Rule', titleRu: 'Travel Rule', kind: 'form' },
      { slug: 'statement', titleEn: 'Account Statement', titleRu: 'Выписка', kind: 'form' },
      { slug: 'balances-by-asset', titleEn: 'Balances by Asset', titleRu: 'Балансы по активам', kind: 'table' },
      { slug: 'pnl-overview', titleEn: 'PnL Overview', titleRu: 'Обзор PnL', kind: 'dashboard' },
      { slug: 'unrealized-pnl', titleEn: 'Unrealized PnL', titleRu: 'Нереализованный PnL', kind: 'dashboard' },
      { slug: 'asset-allocation', titleEn: 'Asset Allocation', titleRu: 'Распределение активов', kind: 'dashboard' },
      { slug: 'dust-convert', titleEn: 'Dust Convert', titleRu: 'Конвертация пыли', kind: 'form' },
      { slug: 'auto-invest-wallet', titleEn: 'Auto-Invest Wallet', titleRu: 'Кошелёк автоинвеста', kind: 'dashboard' },
    ],
  },
  {
    id: 'earn',
    titleEn: 'Earn',
    titleRu: 'Earn и продукты',
    features: [
      { slug: 'simple-earn', titleEn: 'Simple Earn', titleRu: 'Simple Earn', kind: 'table' },
      { slug: 'flexible-savings', titleEn: 'Flexible Savings', titleRu: 'Гибкие накопления', kind: 'table' },
      { slug: 'locked-savings', titleEn: 'Locked Savings', titleRu: 'Срочные накопления', kind: 'table' },
      { slug: 'staking', titleEn: 'Staking', titleRu: 'Стейкинг', kind: 'table' },
      { slug: 'liquid-staking', titleEn: 'Liquid Staking', titleRu: 'Ликвидный стейкинг', kind: 'table' },
      { slug: 'dual-investment', titleEn: 'Dual Investment', titleRu: 'Dual Investment', kind: 'form' },
      { slug: 'structured-products', titleEn: 'Structured Products', titleRu: 'Структурные продукты', kind: 'table' },
      { slug: 'launchpool', titleEn: 'Launchpool', titleRu: 'Launchpool', kind: 'table' },
      { slug: 'launchpad', titleEn: 'Launchpad', titleRu: 'Launchpad', kind: 'table' },
      { slug: 'megadrop', titleEn: 'MegaDrop', titleRu: 'MegaDrop', kind: 'table' },
      { slug: 'airdrops', titleEn: 'Airdrops Hub', titleRu: 'Хаб аирдропов', kind: 'table' },
      { slug: 'vip-loan', titleEn: 'VIP Loan', titleRu: 'VIP-займы', kind: 'form' },
      { slug: 'crypto-loan', titleEn: 'Crypto Loan', titleRu: 'Криптозаймы', kind: 'form' },
      { slug: 'auto-invest', titleEn: 'Auto Invest', titleRu: 'Автоинвест', kind: 'bot' },
      { slug: 'eth-staking', titleEn: 'ETH Staking', titleRu: 'ETH стейкинг', kind: 'form' },
      { slug: 'sol-staking', titleEn: 'SOL Staking', titleRu: 'SOL стейкинг', kind: 'form' },
      { slug: 'rewards-center', titleEn: 'Rewards Center', titleRu: 'Центр наград', kind: 'dashboard' },
      { slug: 'cashback', titleEn: 'Fee Cashback', titleRu: 'Кэшбек комиссий', kind: 'dashboard' },
      { slug: 'referral-earn', titleEn: 'Referral Earn', titleRu: 'Реферальный доход', kind: 'dashboard' },
      { slug: 'coupon-center', titleEn: 'Coupon Center', titleRu: 'Купоны', kind: 'table' },
      { slug: 'voucher', titleEn: 'Vouchers', titleRu: 'Ваучеры', kind: 'table' },
      { slug: 'task-center', titleEn: 'Task Center', titleRu: 'Центр заданий', kind: 'table' },
    ],
  },
  {
    id: 'tools',
    titleEn: 'Tools',
    titleRu: 'Инструменты и аналитика',
    features: [
      { slug: 'pnl-calculator', titleEn: 'PnL Calculator', titleRu: 'Калькулятор PnL', kind: 'calc' },
      { slug: 'liquidation-calculator', titleEn: 'Liquidation Calculator', titleRu: 'Калькулятор ликвидации', kind: 'calc' },
      { slug: 'funding-calculator', titleEn: 'Funding Calculator', titleRu: 'Калькулятор фандинга', kind: 'calc' },
      { slug: 'apr-apy', titleEn: 'APR/APY Converter', titleRu: 'APR/APY конвертер', kind: 'calc' },
      { slug: 'position-size', titleEn: 'Position Size', titleRu: 'Размер позиции', kind: 'calc' },
      { slug: 'risk-reward', titleEn: 'Risk/Reward', titleRu: 'Risk/Reward', kind: 'calc' },
      { slug: 'breakeven', titleEn: 'Breakeven Calculator', titleRu: 'Безубыток', kind: 'calc' },
      { slug: 'fee-calculator', titleEn: 'Fee Calculator', titleRu: 'Калькулятор комиссий', kind: 'calc' },
      { slug: 'price-alerts', titleEn: 'Price Alerts', titleRu: 'Ценовые алерты', kind: 'form' },
      { slug: 'funding-alerts', titleEn: 'Funding Alerts', titleRu: 'Алерты фандинга', kind: 'form' },
      { slug: 'watchlist', titleEn: 'Watchlist', titleRu: 'Список наблюдения', kind: 'table' },
      { slug: 'multi-chart', titleEn: 'Multi Chart', titleRu: 'Мульти-чарт', kind: 'dashboard' },
      { slug: 'tradingview-layout', titleEn: 'Chart Layouts', titleRu: 'Макеты графиков', kind: 'dashboard' },
      { slug: 'technical-indicators', titleEn: 'Indicators Library', titleRu: 'Библиотека индикаторов', kind: 'table' },
      { slug: 'economic-calendar', titleEn: 'Economic Calendar', titleRu: 'Экономический календарь', kind: 'table' },
      { slug: 'news-feed', titleEn: 'News Feed', titleRu: 'Лента новостей', kind: 'table' },
      { slug: 'sentiment', titleEn: 'Market Sentiment', titleRu: 'Сентимент рынка', kind: 'dashboard' },
      { slug: 'correlation', titleEn: 'Correlation Matrix', titleRu: 'Матрица корреляций', kind: 'dashboard' },
      { slug: 'volatility', titleEn: 'Volatility Lab', titleRu: 'Лаборатория волатильности', kind: 'dashboard' },
      { slug: 'portfolio-analyzer', titleEn: 'Portfolio Analyzer', titleRu: 'Анализ портфеля', kind: 'dashboard' },
      { slug: 'tax-report', titleEn: 'Tax Report', titleRu: 'Налоговый отчёт', kind: 'form' },
      { slug: 'api-playground', titleEn: 'API Playground', titleRu: 'API песочница', kind: 'form' },
      { slug: 'webhook-builder', titleEn: 'Webhook Builder', titleRu: 'Конструктор вебхуков', kind: 'form' },
      { slug: 'backtester', titleEn: 'Strategy Backtester', titleRu: 'Бэктестер', kind: 'form' },
      { slug: 'paper-trading', titleEn: 'Paper Trading', titleRu: 'Бумажная торговля', kind: 'trade' },
      { slug: 'demo-funds', titleEn: 'Demo Funds', titleRu: 'Демо-средства', kind: 'form' },
      { slug: 'risk-dashboard', titleEn: 'Risk Dashboard', titleRu: 'Риск-дашборд', kind: 'dashboard' },
      { slug: 'exposure', titleEn: 'Exposure Monitor', titleRu: 'Монитор экспозиции', kind: 'dashboard' },
      { slug: 'stress-test', titleEn: 'Stress Test', titleRu: 'Стресс-тест', kind: 'form' },
      { slug: 'scenario-planner', titleEn: 'Scenario Planner', titleRu: 'Сценарный планировщик', kind: 'form' },
    ],
  },
  {
    id: 'account',
    titleEn: 'Account',
    titleRu: 'Аккаунт и безопасность',
    features: [
      { slug: 'profile', titleEn: 'Profile', titleRu: 'Профиль', kind: 'form' },
      { slug: 'kyc', titleEn: 'Identity Verification', titleRu: 'Верификация KYC', kind: 'form' },
      { slug: 'security', titleEn: 'Security Center', titleRu: 'Центр безопасности', kind: 'dashboard' },
      { slug: '2fa', titleEn: 'Two-Factor Auth', titleRu: 'Двухфакторная аутентификация', kind: 'form' },
      { slug: 'passkeys', titleEn: 'Passkeys', titleRu: 'Passkeys', kind: 'form' },
      { slug: 'anti-phishing', titleEn: 'Anti-Phishing Code', titleRu: 'Антифишинг-код', kind: 'form' },
      { slug: 'device-management', titleEn: 'Devices', titleRu: 'Устройства', kind: 'table' },
      { slug: 'login-history', titleEn: 'Login History', titleRu: 'История входов', kind: 'table' },
      { slug: 'api-keys', titleEn: 'API Keys', titleRu: 'API-ключи', kind: 'table' },
      { slug: 'api-permissions', titleEn: 'API Permissions', titleRu: 'Права API', kind: 'form' },
      { slug: 'sub-accounts', titleEn: 'Sub-Accounts', titleRu: 'Субаккаунты', kind: 'table' },
      { slug: 'preferences', titleEn: 'Preferences', titleRu: 'Настройки', kind: 'form' },
      { slug: 'language-region', titleEn: 'Language & Region', titleRu: 'Язык и регион', kind: 'form' },
      { slug: 'notifications-settings', titleEn: 'Notification Settings', titleRu: 'Настройки уведомлений', kind: 'form' },
      { slug: 'privacy', titleEn: 'Privacy Controls', titleRu: 'Конфиденциальность', kind: 'form' },
      { slug: 'sessions', titleEn: 'Active Sessions', titleRu: 'Активные сессии', kind: 'table' },
      { slug: 'freeze-account', titleEn: 'Freeze Account', titleRu: 'Заморозка аккаунта', kind: 'form' },
      { slug: 'close-account', titleEn: 'Close Account', titleRu: 'Закрытие аккаунта', kind: 'form' },
      { slug: 'vip-levels', titleEn: 'VIP Levels', titleRu: 'VIP-уровни', kind: 'dashboard' },
      { slug: 'fee-tier', titleEn: 'Fee Tier', titleRu: 'Тариф комиссий', kind: 'dashboard' },
      { slug: 'referral', titleEn: 'Referral Program', titleRu: 'Реферальная программа', kind: 'dashboard' },
      { slug: 'affiliate', titleEn: 'Affiliate', titleRu: 'Партнёрка', kind: 'dashboard' },
      { slug: 'messages', titleEn: 'Messages', titleRu: 'Сообщения', kind: 'link', href: '/messages' },
      { slug: 'favorites', titleEn: 'Favorites', titleRu: 'Избранное', kind: 'link', href: '/favorites' },
      { slug: 'support', titleEn: 'Support', titleRu: 'Поддержка', kind: 'link', href: '/support' },
      { slug: 'tickets', titleEn: 'Support Tickets', titleRu: 'Тикеты поддержки', kind: 'table' },
      { slug: 'announcements', titleEn: 'Announcements', titleRu: 'Объявления', kind: 'table' },
      { slug: 'help-center', titleEn: 'Help Center', titleRu: 'Центр помощи', kind: 'table' },
      { slug: 'fees', titleEn: 'Fee Schedule', titleRu: 'Таблица комиссий', kind: 'table' },
      { slug: 'limits', titleEn: 'Trading Limits', titleRu: 'Лимиты торговли', kind: 'dashboard' },
      { slug: 'compliance', titleEn: 'Compliance Center', titleRu: 'Комплаенс', kind: 'dashboard' },
    ],
  },
  {
    id: 'institutional',
    titleEn: 'Institutional',
    titleRu: 'Институциональные',
    features: [
      { slug: 'prime-brokerage', titleEn: 'Prime Brokerage', titleRu: 'Прайм-брокеридж', kind: 'dashboard' },
      { slug: 'custody', titleEn: 'Custody', titleRu: 'Кастоди', kind: 'dashboard' },
      { slug: 'settlement', titleEn: 'Settlement', titleRu: 'Сеттлмент', kind: 'table' },
      { slug: 'rfq', titleEn: 'RFQ Desk', titleRu: 'RFQ-деск', kind: 'form' },
      { slug: 'liquidity-programs', titleEn: 'Liquidity Programs', titleRu: 'Программы ликвидности', kind: 'table' },
      { slug: 'market-maker', titleEn: 'Market Maker Portal', titleRu: 'Портал маркет-мейкера', kind: 'dashboard' },
      { slug: 'fund-admin', titleEn: 'Fund Admin', titleRu: 'Админ фонда', kind: 'dashboard' },
      { slug: 'audit-export', titleEn: 'Audit Export', titleRu: 'Аудит-экспорт', kind: 'form' },
      { slug: 'sla-status', titleEn: 'SLA Status', titleRu: 'SLA статус', kind: 'dashboard' },
      { slug: 'white-label', titleEn: 'White Label', titleRu: 'White Label', kind: 'dashboard' },
    ],
  },
  {
    id: 'assets',
    titleEn: 'Assets',
    titleRu: 'Хабы активов',
    features: [
      { slug: 'asset-btc', titleEn: 'BTC Hub', titleRu: 'Хаб BTC', kind: 'dashboard' },
      { slug: 'asset-eth', titleEn: 'ETH Hub', titleRu: 'Хаб ETH', kind: 'dashboard' },
      { slug: 'asset-sol', titleEn: 'SOL Hub', titleRu: 'Хаб SOL', kind: 'dashboard' },
      { slug: 'asset-bnb', titleEn: 'BNB Hub', titleRu: 'Хаб BNB', kind: 'dashboard' },
      { slug: 'asset-xrp', titleEn: 'XRP Hub', titleRu: 'Хаб XRP', kind: 'dashboard' },
      { slug: 'asset-ada', titleEn: 'ADA Hub', titleRu: 'Хаб ADA', kind: 'dashboard' },
      { slug: 'asset-doge', titleEn: 'DOGE Hub', titleRu: 'Хаб DOGE', kind: 'dashboard' },
      { slug: 'asset-ton', titleEn: 'TON Hub', titleRu: 'Хаб TON', kind: 'dashboard' },
      { slug: 'asset-avax', titleEn: 'AVAX Hub', titleRu: 'Хаб AVAX', kind: 'dashboard' },
      { slug: 'asset-dot', titleEn: 'DOT Hub', titleRu: 'Хаб DOT', kind: 'dashboard' },
      { slug: 'asset-link', titleEn: 'LINK Hub', titleRu: 'Хаб LINK', kind: 'dashboard' },
      { slug: 'asset-matic', titleEn: 'MATIC Hub', titleRu: 'Хаб MATIC', kind: 'dashboard' },
      { slug: 'asset-atom', titleEn: 'ATOM Hub', titleRu: 'Хаб ATOM', kind: 'dashboard' },
      { slug: 'asset-near', titleEn: 'NEAR Hub', titleRu: 'Хаб NEAR', kind: 'dashboard' },
      { slug: 'asset-apt', titleEn: 'APT Hub', titleRu: 'Хаб APT', kind: 'dashboard' },
      { slug: 'asset-arb', titleEn: 'ARB Hub', titleRu: 'Хаб ARB', kind: 'dashboard' },
      { slug: 'asset-op', titleEn: 'OP Hub', titleRu: 'Хаб OP', kind: 'dashboard' },
      { slug: 'asset-sui', titleEn: 'SUI Hub', titleRu: 'Хаб SUI', kind: 'dashboard' },
      { slug: 'asset-pepe', titleEn: 'PEPE Hub', titleRu: 'Хаб PEPE', kind: 'dashboard' },
      { slug: 'asset-wif', titleEn: 'WIF Hub', titleRu: 'Хаб WIF', kind: 'dashboard' },
      { slug: 'asset-trx', titleEn: 'TRX Hub', titleRu: 'Хаб TRX', kind: 'dashboard' },
      { slug: 'asset-ltc', titleEn: 'LTC Hub', titleRu: 'Хаб LTC', kind: 'dashboard' },
      { slug: 'asset-bch', titleEn: 'BCH Hub', titleRu: 'Хаб BCH', kind: 'dashboard' },
      { slug: 'asset-uni', titleEn: 'UNI Hub', titleRu: 'Хаб UNI', kind: 'dashboard' },
      { slug: 'asset-aave', titleEn: 'AAVE Hub', titleRu: 'Хаб AAVE', kind: 'dashboard' },
      { slug: 'asset-mkr', titleEn: 'MKR Hub', titleRu: 'Хаб MKR', kind: 'dashboard' },
      { slug: 'asset-crv', titleEn: 'CRV Hub', titleRu: 'Хаб CRV', kind: 'dashboard' },
      { slug: 'asset-inj', titleEn: 'INJ Hub', titleRu: 'Хаб INJ', kind: 'dashboard' },
      { slug: 'asset-fil', titleEn: 'FIL Hub', titleRu: 'Хаб FIL', kind: 'dashboard' },
      { slug: 'asset-icp', titleEn: 'ICP Hub', titleRu: 'Хаб ICP', kind: 'dashboard' },
      { slug: 'asset-hbar', titleEn: 'HBAR Hub', titleRu: 'Хаб HBAR', kind: 'dashboard' },
      { slug: 'asset-vet', titleEn: 'VET Hub', titleRu: 'Хаб VET', kind: 'dashboard' },
      { slug: 'asset-algo', titleEn: 'ALGO Hub', titleRu: 'Хаб ALGO', kind: 'dashboard' },
      { slug: 'asset-xlm', titleEn: 'XLM Hub', titleRu: 'Хаб XLM', kind: 'dashboard' },
      { slug: 'asset-eos', titleEn: 'EOS Hub', titleRu: 'Хаб EOS', kind: 'dashboard' },
      { slug: 'asset-ftm', titleEn: 'FTM Hub', titleRu: 'Хаб FTM', kind: 'dashboard' },
      { slug: 'asset-sand', titleEn: 'SAND Hub', titleRu: 'Хаб SAND', kind: 'dashboard' },
      { slug: 'asset-mana', titleEn: 'MANA Hub', titleRu: 'Хаб MANA', kind: 'dashboard' },
      { slug: 'asset-axs', titleEn: 'AXS Hub', titleRu: 'Хаб AXS', kind: 'dashboard' },
      { slug: 'asset-gala', titleEn: 'GALA Hub', titleRu: 'Хаб GALA', kind: 'dashboard' },
      { slug: 'asset-imx', titleEn: 'IMX Hub', titleRu: 'Хаб IMX', kind: 'dashboard' },
      { slug: 'asset-rndr', titleEn: 'RNDR Hub', titleRu: 'Хаб RNDR', kind: 'dashboard' },
      { slug: 'asset-fet', titleEn: 'FET Hub', titleRu: 'Хаб FET', kind: 'dashboard' },
      { slug: 'asset-grt', titleEn: 'GRT Hub', titleRu: 'Хаб GRT', kind: 'dashboard' },
      { slug: 'asset-snx', titleEn: 'SNX Hub', titleRu: 'Хаб SNX', kind: 'dashboard' },
      { slug: 'asset-comp', titleEn: 'COMP Hub', titleRu: 'Хаб COMP', kind: 'dashboard' },
      { slug: 'asset-yfi', titleEn: 'YFI Hub', titleRu: 'Хаб YFI', kind: 'dashboard' },
      { slug: 'asset-ldo', titleEn: 'LDO Hub', titleRu: 'Хаб LDO', kind: 'dashboard' },
      { slug: 'asset-stx', titleEn: 'STX Hub', titleRu: 'Хаб STX', kind: 'dashboard' },
      { slug: 'asset-tia', titleEn: 'TIA Hub', titleRu: 'Хаб TIA', kind: 'dashboard' },
      { slug: 'asset-sei', titleEn: 'SEI Hub', titleRu: 'Хаб SEI', kind: 'dashboard' },
      { slug: 'asset-jup', titleEn: 'JUP Hub', titleRu: 'Хаб JUP', kind: 'dashboard' },
      { slug: 'asset-pyth', titleEn: 'PYTH Hub', titleRu: 'Хаб PYTH', kind: 'dashboard' },
      { slug: 'asset-wld', titleEn: 'WLD Hub', titleRu: 'Хаб WLD', kind: 'dashboard' },
      { slug: 'asset-ordi', titleEn: 'ORDI Hub', titleRu: 'Хаб ORDI', kind: 'dashboard' },
      { slug: 'asset-bonk', titleEn: 'BONK Hub', titleRu: 'Хаб BONK', kind: 'dashboard' },
      { slug: 'asset-floki', titleEn: 'FLOKI Hub', titleRu: 'Хаб FLOKI', kind: 'dashboard' },
      { slug: 'asset-shib', titleEn: 'SHIB Hub', titleRu: 'Хаб SHIB', kind: 'dashboard' },
      { slug: 'asset-not', titleEn: 'NOT Hub', titleRu: 'Хаб NOT', kind: 'dashboard' },
      { slug: 'asset-ena', titleEn: 'ENA Hub', titleRu: 'Хаб ENA', kind: 'dashboard' },
      { slug: 'asset-pendle', titleEn: 'PENDLE Hub', titleRu: 'Хаб PENDLE', kind: 'dashboard' },
      { slug: 'asset-jto', titleEn: 'JTO Hub', titleRu: 'Хаб JTO', kind: 'dashboard' },
      { slug: 'asset-strk', titleEn: 'STRK Hub', titleRu: 'Хаб STRK', kind: 'dashboard' },
      { slug: 'asset-zk', titleEn: 'ZK Hub', titleRu: 'Хаб ZK', kind: 'dashboard' },
      { slug: 'asset-tao', titleEn: 'TAO Hub', titleRu: 'Хаб TAO', kind: 'dashboard' },
      { slug: 'asset-cake', titleEn: 'CAKE Hub', titleRu: 'Хаб CAKE', kind: 'dashboard' },
      { slug: 'asset-rune', titleEn: 'RUNE Hub', titleRu: 'Хаб RUNE', kind: 'dashboard' },
      { slug: 'asset-theta', titleEn: 'THETA Hub', titleRu: 'Хаб THETA', kind: 'dashboard' },
      { slug: 'asset-flow', titleEn: 'FLOW Hub', titleRu: 'Хаб FLOW', kind: 'dashboard' },
      { slug: 'asset-kava', titleEn: 'KAVA Hub', titleRu: 'Хаб KAVA', kind: 'dashboard' },
      { slug: 'asset-neo', titleEn: 'NEO Hub', titleRu: 'Хаб NEO', kind: 'dashboard' },
      { slug: 'asset-etc', titleEn: 'ETC Hub', titleRu: 'Хаб ETC', kind: 'dashboard' },
      { slug: 'asset-dash', titleEn: 'DASH Hub', titleRu: 'Хаб DASH', kind: 'dashboard' },
      { slug: 'asset-zec', titleEn: 'ZEC Hub', titleRu: 'Хаб ZEC', kind: 'dashboard' },
      { slug: 'asset-iota', titleEn: 'IOTA Hub', titleRu: 'Хаб IOTA', kind: 'dashboard' },
      { slug: 'asset-qtum', titleEn: 'QTUM Hub', titleRu: 'Хаб QTUM', kind: 'dashboard' },
      { slug: 'asset-zil', titleEn: 'ZIL Hub', titleRu: 'Хаб ZIL', kind: 'dashboard' },
      { slug: 'asset-waves', titleEn: 'WAVES Hub', titleRu: 'Хаб WAVES', kind: 'dashboard' },
      { slug: 'asset-chz', titleEn: 'CHZ Hub', titleRu: 'Хаб CHZ', kind: 'dashboard' },
      { slug: 'asset-enj', titleEn: 'ENJ Hub', titleRu: 'Хаб ENJ', kind: 'dashboard' },
      { slug: 'asset-bat', titleEn: 'BAT Hub', titleRu: 'Хаб BAT', kind: 'dashboard' },
      { slug: 'asset-zrx', titleEn: 'ZRX Hub', titleRu: 'Хаб ZRX', kind: 'dashboard' },
      { slug: 'asset-ankr', titleEn: 'ANKR Hub', titleRu: 'Хаб ANKR', kind: 'dashboard' },
      { slug: 'asset-celo', titleEn: 'CELO Hub', titleRu: 'Хаб CELO', kind: 'dashboard' },
      { slug: 'asset-one', titleEn: 'ONE Hub', titleRu: 'Хаб ONE', kind: 'dashboard' },
      { slug: 'asset-rose', titleEn: 'ROSE Hub', titleRu: 'Хаб ROSE', kind: 'dashboard' },
      { slug: 'asset-ksm', titleEn: 'KSM Hub', titleRu: 'Хаб KSM', kind: 'dashboard' },
      { slug: 'asset-glmr', titleEn: 'GLMR Hub', titleRu: 'Хаб GLMR', kind: 'dashboard' },
      { slug: 'asset-movr', titleEn: 'MOVR Hub', titleRu: 'Хаб MOVR', kind: 'dashboard' },
      { slug: 'asset-mina', titleEn: 'MINA Hub', titleRu: 'Хаб MINA', kind: 'dashboard' },
      { slug: 'asset-cfx', titleEn: 'CFX Hub', titleRu: 'Хаб CFX', kind: 'dashboard' },
      { slug: 'asset-klay', titleEn: 'KLAY Hub', titleRu: 'Хаб KLAY', kind: 'dashboard' },
      { slug: 'asset-gmt', titleEn: 'GMT Hub', titleRu: 'Хаб GMT', kind: 'dashboard' },
      { slug: 'asset-ape', titleEn: 'APE Hub', titleRu: 'Хаб APE', kind: 'dashboard' },
      { slug: 'asset-lrc', titleEn: 'LRC Hub', titleRu: 'Хаб LRC', kind: 'dashboard' },
      { slug: 'asset-skl', titleEn: 'SKL Hub', titleRu: 'Хаб SKL', kind: 'dashboard' },
      { slug: 'asset-storj', titleEn: 'STORJ Hub', titleRu: 'Хаб STORJ', kind: 'dashboard' },
      { slug: 'asset-ankr2', titleEn: 'ANKR2 Hub', titleRu: 'Хаб ANKR2', kind: 'dashboard' },
      { slug: 'asset-blur', titleEn: 'BLUR Hub', titleRu: 'Хаб BLUR', kind: 'dashboard' },
      { slug: 'asset-mask', titleEn: 'MASK Hub', titleRu: 'Хаб MASK', kind: 'dashboard' },
    ],
  },
];

export const ADMIN_SUITE_FEATURES: ExchangeFeature[] = [
  { slug: 'ops-dashboard', titleEn: 'Ops Dashboard', titleRu: 'Операционный дашборд', kind: 'dashboard' },
  { slug: 'user-risk', titleEn: 'User Risk Scores', titleRu: 'Риск-скоры пользователей', kind: 'table' },
  { slug: 'aml-queue', titleEn: 'AML Queue', titleRu: 'AML очередь', kind: 'table' },
  { slug: 'kyc-queue', titleEn: 'KYC Queue', titleRu: 'KYC очередь', kind: 'table' },
  { slug: 'dispute-board', titleEn: 'Dispute Board', titleRu: 'Доска споров', kind: 'table' },
  { slug: 'fee-revenue', titleEn: 'Fee Revenue', titleRu: 'Доход с комиссий', kind: 'dashboard' },
  { slug: 'spread-analytics', titleEn: 'Spread Analytics', titleRu: 'Аналитика спреда', kind: 'dashboard' },
  { slug: 'house-balances', titleEn: 'House Balances', titleRu: 'Балансы дома', kind: 'dashboard' },
  { slug: 'employee-balances', titleEn: 'Employee Balances', titleRu: 'Балансы сотрудников', kind: 'table' },
  { slug: 'audit-trail', titleEn: 'Audit Trail', titleRu: 'Аудит-лог', kind: 'table' },
  { slug: 'rate-overrides', titleEn: 'Rate Overrides', titleRu: 'Переопределение курсов', kind: 'form' },
  { slug: 'hedge-console', titleEn: 'Hedge Console', titleRu: 'Консоль хеджа', kind: 'link', href: '/admin/hedge' },
  { slug: 'liquidity-monitor', titleEn: 'Liquidity Monitor', titleRu: 'Монитор ликвидности', kind: 'dashboard' },
  { slug: 'alert-rules', titleEn: 'Alert Rules', titleRu: 'Правила алертов', kind: 'form' },
  { slug: 'feature-flags', titleEn: 'Feature Flags', titleRu: 'Feature flags', kind: 'table' },
  { slug: 'maintenance-mode', titleEn: 'Maintenance Mode', titleRu: 'Режим обслуживания', kind: 'form' },
  { slug: 'announcement-editor', titleEn: 'Announcement Editor', titleRu: 'Редактор анонсов', kind: 'form' },
  { slug: 'support-inbox', titleEn: 'Support Inbox', titleRu: 'Инбокс поддержки', kind: 'table' },
  { slug: 'compliance-reports', titleEn: 'Compliance Reports', titleRu: 'Комплаенс-отчёты', kind: 'table' },
  { slug: 'settlement-batch', titleEn: 'Settlement Batch', titleRu: 'Батч сеттлмента', kind: 'form' },
  { slug: 'wallet-sweep', titleEn: 'Wallet Sweep', titleRu: 'Свип кошельков', kind: 'form' },
  { slug: 'cold-wallet', titleEn: 'Cold Wallet Ops', titleRu: 'Холодный кошелёк', kind: 'dashboard' },
  { slug: 'hot-wallet', titleEn: 'Hot Wallet Ops', titleRu: 'Горячий кошелёк', kind: 'dashboard' },
  { slug: 'reconciliation', titleEn: 'Reconciliation', titleRu: 'Сверка', kind: 'table' },
  { slug: 'incident-center', titleEn: 'Incident Center', titleRu: 'Инцидент-центр', kind: 'table' },
  { slug: 'settings-hub', titleEn: 'Platform Settings', titleRu: 'Настройки платформы', kind: 'form' },
  { slug: 'employee-roles', titleEn: 'Employee Roles', titleRu: 'Роли сотрудников', kind: 'table' },
  { slug: 'p2p-queue', titleEn: 'P2P Queue', titleRu: 'Очередь P2P', kind: 'link', href: '/admin/queue' },
  { slug: 'rates-console', titleEn: 'Rates Console', titleRu: 'Консоль курсов', kind: 'link', href: '/admin/rates' },
  { slug: 'treasury-console', titleEn: 'Treasury Console', titleRu: 'Казначейство', kind: 'link', href: '/admin/treasury' },
];

export function allFeatures(): ExchangeFeature[] {
  return EXCHANGE_CATEGORIES.flatMap((c) => c.features);
}

export function findFeature(slug: string): ExchangeFeature | undefined {
  return allFeatures().find((f) => f.slug === slug) ?? ADMIN_SUITE_FEATURES.find((f) => f.slug === slug);
}

export function findCategory(id: string): ExchangeCategory | undefined {
  return EXCHANGE_CATEGORIES.find((c) => c.id === id);
}

export const TOTAL_EXCHANGE_FEATURES = 299;
